kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
data:
  ssl-ciphers: "ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384"
  #ssl-ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-CCM:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-CCM:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256"
  #ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-CCM:ECDHE-ECDSA-AES256-CCM:ECDHE-ECDSA-AES128-CBC-SHA256:ECDHE-ECDSA-AES256-CBC-SHA384:ECDHE-ECDSA-AES128-CBC-SHA:ECDHE-ECDSA-AES256-CBC-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-CBC-SHA256:ECDHE-RSA-AES256-CBC-SHA384:ECDHE-RSA-AES128-CBC-SHA:ECDHE-RSA-AES256-CBC-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:DHE-RSA-AES128-CCM:DHE-RSA-AES256-CCM:DHE-DSS-AES128-CBC-SHA256:DHE-RSA-AES128-CBC-SHA256:DHE-DSS-AES256-CBC-SHA256:DHE-RSA-AES256-CBC-SHA256:DHE-DSS-AES128-CBC-SHA:DHE-RSA-AES128-CBC-SHA:DHE-DSS-AES256-CBC-SHA:DHE-RSA-AES256-CBC-SHA:RSA-AES128-GCM-SHA256:RSA-AES256-GCM-SHA384:RSA-AES128-CCM:RSA-AES256-CCM:RSA-AES128-CBC-SHA256:RSA-AES256-CBC-SHA256:RSA-AES128-CBC-SHA:RSA-AES256-CBC-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256TLS-AES128-CCM-SHA256:AES128-CCM8-SHA256"
  ssl-session-cache: "true"
  ssl-session-timeout: "10m"
  proxy_connect_timeout: "600"
  proxy_send_timeout: "600"
  proxy_read_timeout: "600"
  send_timeout: "600"
  fastcgi_send_timeout: "1200s"
  fastcgi_read_timeout: "1200s"