apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx"},"name":"ingress-nginx","namespace":"ingress-nginx"},"spec":{"externalTrafficPolicy":"Local","ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":"http"},{"name":"https","port":443,"protocol":"TCP","targetPort":"https"}],"selector":{"app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx"},"type":"LoadBalancer"}}
      annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: tbs-prod-static-ip
  creationTimestamp: "2020-01-13T16:27:01Z"
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx
  namespace: ingress-nginx
  resourceVersion: "132941"
  selfLink: /api/v1/namespaces/ingress-nginx/services/ingress-nginx
spec:
  clusterIP: 10.0.15.186
  externalTrafficPolicy: Local
  healthCheckNodePort: 31308
  ports:
  - name: http
    nodePort: 30601
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30531
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 52.237.15.42
